version: '3.8'

services:
  agentic-tools-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentic-tools-mcp:latest
    container_name: agentic-tools-mcp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Map host paths to container paths - must match the volume mounts below
      - PATH_MAPPING=/Users/jasonschulz/Developer:/Users/jasonschulz/Developer,/Users/jasonschulz/Documents:/Users/jasonschulz/Documents,/Users/jasonschulz/Desktop:/Users/jasonschulz/Desktop
    volumes:
      # Map your directories - paths inside container match host paths for simplicity
      # Developer directory (for code projects)
      - /Users/jasonschulz/Developer:/Users/jasonschulz/Developer
      # Documents directory (for document-based projects)
      - /Users/jasonschulz/Documents:/Users/jasonschulz/Documents
      # Desktop directory (for quick access)
      - /Users/jasonschulz/Desktop:/Users/jasonschulz/Desktop
      
      # Alternative: Map entire home directory (simpler but less secure)
      # - /Users/jasonschulz:/Users/jasonschulz
      # Then use PATH_MAPPING=/Users/jasonschulz:/Users/jasonschulz
      
      # Storage volumes
      - ./data:/app/.agentic-tools-mcp
      - ~/.agentic-tools-mcp:/data/.agentic-tools-mcp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => { process.exit(1); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s