version: '3.8'

services:
  agentic-tools-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: agentic-tools-mcp:latest
    container_name: agentic-tools-mcp
    ports:
      - "3000:3000"
    environment:
      # Node.js environment
      - NODE_ENV=production
      # Optional: Enable global directory mode by default
      # - CLAUDE_FLAG=true
      # Path mapping for host filesystem access (required for project directories)
      # Format: "host_path:container_path,host_path2:container_path2"
      # Example: "/Users:/workspace/Users,/home:/workspace/home"
      # - PATH_MAPPING=/Users:/workspace/Users
    volumes:
      # Mount local storage directory for persistence
      # For project-specific storage (default)
      - ./data:/app/.agentic-tools-mcp
      # For global storage (when using --claude flag or header)
      - ~/.agentic-tools-mcp:/data/.agentic-tools-mcp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => { process.exit(1); })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Optional: Add a volume for persistent storage
volumes:
  agentic-tools-data:
    driver: local